env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-snap
    cpu: 8
    memory: 8G
  install_script:
    - pkg install -y
      bash bison curl cyrus-sasl git glib gmake gnutls gsed
      nettle perl5 pixman pkgconf png usbredir py36-pip
      pip-3.6 install virtualenv
    - pip-3.6 install virtualenv
    - export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.6
  script:
    - mkdir build
    - cd build
    - ../configure || { cat config.log; exit 1; }
    - gmake -j8
    - gmake -j8 V=1 check
    - gmake check-acceptance

macos_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install pkg-config python gnu-sed glib pixman make sdl2
  script:
    - mkdir build
    - cd build
    - ../configure --python=/usr/local/bin/python3 || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake check -j$(sysctl -n hw.ncpu)
    - gmake check-acceptance

macos_xcode_task:
  osx_instance:
    # this is an alias for the latest Xcode
    image: mojave-xcode
  install_script:
    - brew install pkg-config gnu-sed glib pixman make sdl2
  script:
    - mkdir build
    - cd build
    - ../configure --cc=clang || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake check -j$(sysctl -n hw.ncpu)
    - gmake check-acceptance
