osx_mojave_task:
  osx_instance:
    matrix:
      image: mojave-base
      image: high-sierra-base
  env:
    CIRRUS_CLONE_DEPTH: 1
  install_script: brew install
    autoconf
    automake
    llvm
    libffi
    libgcrypt
    libiscsi
    libpng
    libssh2
    libtasn1
    libusb
    lzfse
    lzo
    gettext
    glib
    gnutls
    jpeg
    ncurses
    nettle
    pixman
    pkg-config
    snappy
#    spice-protocol (mojave-base)
    vde
  script:
    - mkdir build
    - cd build
    - ../configure
      --enable-cocoa
      --extra-cflags=-mavx2
      --target-list=aarch64-softmmu,i386-softmmu,lm32-softmmu,m68k-softmmu,mips-softmmu,mips64el-softmmu,nios2-softmmu,ppc64-softmmu,riscv32-softmmu,riscv64-softmmu,s390x-softmmu,sh4-softmmu,sparc-softmmu,sparc64-softmmu,tricore-softmmu,x86_64-softmmu,xtensa-softmmu
      || { cat config.log; exit 1; }
    - make -j2
    - make -j2 V=1 check
