osx_mojave_task:
  osx_instance:
    image: mojave-base
  env:
    CIRRUS_CLONE_DEPTH: 1
  install_script: brew install
    llvm libffi gettext glib pkg-config autoconf automake pixman
  script:
    - mkdir build
    - cd build
    - ../configure || { cat config.log; exit 1; }
    - gmake -j8
    - gmake -j8 V=1 check

#./configure --prefix=/Users/sebastian/Developer/Cellar/qemu/0.13.0 --disable-darwin-user --enable-cocoa --disable-bsd-user

