env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 8
    memory: 8G
  install_script:
    - pkg update -f
    - pkg install -y
      bash bison curl cyrus-sasl git glib gmake gnutls gsed
      nettle perl5 pixman pkgconf png usbredir
  script:
    - mkdir build
    - cd build
    - ../configure || { cat config.log; exit 1; }
  build_script:
    - gmake -C build -j8
  test_script:
    - gmake -C build -j8 V=1 check

macos_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install pkg-config python gnu-sed glib pixman make sdl2
  configure_script:
    - mkdir build
    - cd build
    - ../configure || { cat config.log; exit 1; }
  build_script:
    - gmake -C build -j$(sysctl -n hw.ncpu)
  test_script:
    - gmake -C build check -j$(sysctl -n hw.ncpu)

macos_xcode_task:
  osx_instance:
    # this is an alias for the latest Xcode
    image: mojave-xcode
  install_script:
    - brew install pkg-config gnu-sed glib pixman make sdl2
  configure_script:
    - mkdir build
    - cd build
    - ../configure --cc=clang || { cat config.log; exit 1; }
  build_script:
    - gmake -C build -j$(sysctl -n hw.ncpu)
  test_script:
    - gmake -C build check -j$(sysctl -n hw.ncpu)
