language: c
git:
   submodules: false
env:
  global:
    - LC_ALL=C
  matrix:
    - IMAGE=fedora
      TARGET_LIST=arm-softmmu,i386-softmmu,lm32-softmmu,aarch64-softmmu,sparc64-softmmu,x86_64-softmmu
      EXTRA_CONFIGURE_FLAGS="--cross-prefix=i686-w64-mingw32- --extra-cflags='--disable-werror --disable-stack-protector'"
build:
  pre_ci:
    - make docker-image-${IMAGE} V=1
  pre_ci_boot:
    image_name: qemu
    image_tag: ${IMAGE}
    pull: false
    options: "-e HOME=/root"
  ci:
    - unset CC
    - ./configure ${QEMU_CONFIGURE_OPTS} ${EXTRA_CONFIGURE_FLAGS} --target-list=${TARGET_LIST}
    - make -j$(($(getconf _NPROCESSORS_ONLN) + 1))
