language: c
git:
   submodules: false
env:
  global:
    - LC_ALL=C
  matrix:
    - IMAGE=fedora-edk2
      TARGET_LIST=i386-softmmu,x86_64-softmmu,aarch64-softmmu
      MAKE_ARGS=-C roms efi
build:
  pre_ci:
    # usually host ARCH is set by configure
    - echo "ARCH=$(uname -m)" > config-host.mak
    - make docker-image-${IMAGE} V=1
  pre_ci_boot:
    image_name: qemu
    image_tag: ${IMAGE}
    pull: false
    options: "-e HOME=/root"
  ci:
    - unset CC
    - ./configure ${QEMU_CONFIGURE_OPTS} --target-list=${TARGET_LIST}
    - make -j$(($(getconf _NPROCESSORS_ONLN) + 1)) ${MAKE_ARGS}
