language: c
git:
   submodules: false
env:
  global:
    - LC_ALL=C
    - PRE_CONFIGURE_COMMANDS="unset CC"
  matrix:
    - IMAGE=debian-amd64
      TARGET_LIST=x86_64-softmmu,x86_64-linux-user
    - IMAGE=debian-win32-cross
      TARGET_LIST=arm-softmmu,i386-softmmu,lm32-softmmu
    - IMAGE=debian-win64-cross
      TARGET_LIST=aarch64-softmmu,sparc64-softmmu,x86_64-softmmu
    - IMAGE=debian-armel-cross
      TARGET_LIST=arm-softmmu,arm-linux-user,armeb-linux-user
    - IMAGE=debian-armhf-cross
      TARGET_LIST=arm-softmmu,arm-linux-user,armeb-linux-user
    - IMAGE=debian-arm64-cross
      TARGET_LIST=aarch64-softmmu,aarch64-linux-user
    - IMAGE=debian-s390x-cross
      TARGET_LIST=s390x-softmmu,s390x-linux-user
    - IMAGE=debian-mips-cross
      TARGET_LIST=mips-softmmu,mipsel-linux-user
    - IMAGE=debian-mips64el-cross
      TARGET_LIST=mips64el-softmmu,mips64el-linux-user
    - IMAGE=debian-ppc64el-cross
      TARGET_LIST=ppc64-softmmu,ppc64-linux-user,ppc64abi32-linux-user
    - IMAGE=fedora-edk2
      TARGET_LIST=i386-softmmu,x86_64-softmmu,aarch64-softmmu
      PRE_CONFIGURE_COMMANDS="unset CC && git submodule update --init --recursive roms/edk2"
      MAKE_ARGS="-C roms efi"
build:
  pre_ci:
    # usually host ARCH is set by configure
    - echo "ARCH=$(uname -m)" > config-host.mak
    - make docker-image-${IMAGE} V=1
  pre_ci_boot:
    image_name: qemu
    image_tag: ${IMAGE}
    pull: false
    options: "-e HOME=/root"
  ci:
    - ${PRE_CONFIGURE_COMMANDS}
    - ./configure ${QEMU_CONFIGURE_OPTS} --target-list=${TARGET_LIST}
    # Console size exceeds 16 MB limit. Truncated from here.
    - make -j$(($(getconf _NPROCESSORS_ONLN) + 1)) ${MAKE_ARGS} > build.log 2>&1 || ( tail -c 14M build.log; false )
