version: 1.0.{build}

clone_depth: 3
#shallow_clone: true

#image: Visual Studio 2017
image:
- Ubuntu1604
- Ubuntu1804

install:
- git submodule update --init --recursive ui/keycodemapdb

environment:
  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  MY_VAR: value1
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  MY_VAR: value2
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      QEMU_CONFIGURE_OPTS: --cross-prefix=x86_64-w64-mingw32-

build_script:
- sh: PATH=/mingw64/bin:$PATH bash ./configure $QEMU_CONFIGURE_OPTS
- sh: make msi

test: off
