# Default configuration for armeb-softmmu

CONFIG_ECC=y
CONFIG_SERIAL=y
CONFIG_PTIMER=y
CONFIG_SD=y
CONFIG_SSI=y
CONFIG_SSI_SD=y
#CONFIG_USB=y
#CONFIG_USB_EHCI_SYSBUS=y
CONFIG_PLATFORM_BUS=y

CONFIG_ARM_V7M=y
CONFIG_ARM_GIC=y
CONFIG_ARM_TIMER=y
CONFIG_PL011=y
CONFIG_PL022=y
CONFIG_PL031=y
CONFIG_PL041=y
CONFIG_PL050=y
CONFIG_PL061=y
CONFIG_PL080=y
#CONFIG_PL110=y
CONFIG_PL181=y
CONFIG_PL190=y
CONFIG_PL310=y
CONFIG_PL330=y

CONFIG_BITBANG_I2C=y
CONFIG_GPIO_KEY=y
